src/css/base.scss, src/index.html
-Begins the splash page.
-Might update colors to make everything a little more legible
-Trying to stack labels on top of text area
-No JS functionality yet
=> Splash page

src/css/base.scss, src/index.html
- Adds basic template for gameplay page
- Want to fix answer inputs to look nicer
- Eventually add animations to table
- Add infobox animation
=> Gameplay page

src/domUpdates.js, src/index.html, src/index.js
Added api data to the app.
start on 18 index.js
=> Api feature

src/domUpdates.js, src/index.html
=> Fix merge conflicts

src/game.js, src/index.js, src/round.js, src/turn.js, test/game-test.js, test/round-test.js, test/turn-test.js
this PR adds test for classes. 
start on the player class 
all test are passing or skipped.
all skipped test are methods or related to methods.
@hannahhch, @khalidwilliams, @brittanystoroz
=> Make tests

src/css/base.scss, src/data.js, src/domUpdates.js, src/game.js, src/index.html, src/index.js, src/round.js
Creates function to randomize a number based on number of surveys and pulls that survey
on domUpdates.js, there is a randomizeSurvey()
Some code may be changed shortly based on where we are pulling data from.  This code currently pulls from data.js 
Next step is to get the answers that match with the survey question
=> Random survey

src/domUpdates.js, src/game.js, src/index.js, test/game-test.js
Added game methods and passed many tests.
I have the game holding the data but not sure if im not importing it the right way others cannot access the data.
changed game1 to game. 
i have a function starting the in the api data function
look at the game class page. i have it taking 3 surveys just the first three
=> Feature game class

src/css/base.scss, src/domUpdates.js, src/game.js, src/index.html, src/index.js
Refactor domUpdates to align with planned structure
domUpdates.js
Some functions existed that did not strictly update DOM
Navigating through game and player class seems to be tricky but appended html was moved back to html to keep things simple.
=> Refactor dom updates

src/domUpdates.js, src/index.js, src/player.js
Continues to refactor domUpdates
domUpdates.js
Restructuring of application calls for refactoring
We are all here in person so we are syncing up master
=> Refactor dom updates part 2

src/domUpdates.js, src/game.js, src/index.js, src/round.js, test/game-test.js, test/round-test.js
start on Game
added the findSurveys() method which gets 3 surveys and 3 answers for each survey.
test does not pass for that. but it is return to the console
=> Feature play

src/domUpdates.js, src/game.js, src/index.html
- Loads up a new set of answers, surveys, and respondents
=> Dom display

src/domUpdates.js, src/game.js, src/index.html, test/game-test.js, test/player-test.js
Adds beforeEach for spies
Adds afterEach hook for cleaning up spies
Adds spies for the 4 methods used
Fixes issues on surveys not loading on DOM
game-test.js and player-test.js
Running npm test, we received an error about window not being defined because tests were being run on a non-existent DOM
=> Fix issues

src/game.js, src/index.js
- This commit adds a variable in `index.js` for the text input and submit button on the question page.
- Creates a function that contains an empty array, and for the current survey (currently the zero index of the 3 pre-loaded surveys) pushes each answer into that array. 
- Uses `.includes()` method to compare the input to the answers from pre-loaded surveys
NEXT STEPS:
- Flip cards upon the correct answer being entered, 
- Update score upon correct answer
=> is able to match the answer input to the responses of the survey

src/css/base.scss, src/domUpdates.js, src/index.html, src/index.js
This PR give quit game and restart game abilities  to the game. 
look at: 
newGameBtn() 
restartGame() 
quitGame()
backToGame() 
in domUpdates 
and 
$(".new-game-btn-check").click(domUpdates.restartGame)
$(".new-game-btn-go-back").click(domUpdates.backToGame);
$('.quit-game-btn').click(domUpdates.quitGame)
in index.js
=> Quit start

src/css/base.scss, src/index.html, src/index.js
- Adjusts layout of responses and flip function(still needs work)
- Change some divs to spans for predefined inline block property
- Add flip functionality when a match in user input is found
- index.js
- Input answers into input space
- Matching is not case specific but is still character specific
- Layout will continue to be worked on
=> Response func

src/domUpdates.js
adjusted method so that it just restarts game
=> added restart instead of save user

src/domUpdates.js, src/index.js, src/player.js
- This PR adds ability to take turns with two players
- On web application, index.js, player.js, and domUpdates.js
- On web application, check scores between answer inputs
- New parameter for two methods were added to check whos turn it was
=> Change turn

src/css/base.scss, src/index.html, src/index.js
=> Toggleplayer

src/domUpdates.js, src/game.js, src/index.html, src/index.js
- Advance user to next round
- Created issue for info button
=> Next round

src/css/base.scss, src/domUpdates.js, src/index.html
- finishes styling on winner page depending on the winner (zombie/ninja)
=> Win page styling

src/css/base.scss, src/index.html, src/index.js
On new rounds, a display pops up that shows which current round is
=> Round display

src/css/base.scss, src/index.html, src/index.js
- Adds leaderboard
- index.js
- Get high score and refresh page
- First use of post
=> Leaderboard

src/css/_variables.scss, src/css/base.scss
What's this PR do?
add sass variables and _variables file and mixin
Where should the reviewer start?
base.sass _variables.sass
How should this be manually tested?
make sure colors and shadows work
=> Sass clean

test/game-test.js, test/round-test.js, test/turn-test.js
Where to start:
check all test files all test pass 
test that were not used were removed
=> Test clean

test/game-test.js
Remove instances where previously attempted Turn class were present
=> Remove turn case
